let basis = {
    mainColor: "rgb(65, 184, 131)",
    subColor: "rgb(165, 184, 131)",
};
export const GridParams = {
    g_2: {
        name: "双栏",
        label: "hope_grid",
        icon: "icon-anniu",
        isSelected: false,
        event: "",
        defaultClass: "hope_grid",
        customClass: "g_100",
        style: {
            width: "100%",
        },
        effect: {},
        layout: {},
        children: [
            {
                name: "2_1",
                label: "hope_grid",
                icon: "icon-anniu",
                isSelected: false,
                event: "",
                defaultClass: "hope_grid",
                customClass: "g_50",
                style: {
                    width: "50%",
                    height: "500px",
                },
                effect: {},
                layout: {
                    paddingTop: "50px",
                    paddingBottom: "50px",
                    paddingLeft: "20px",
                    paddingRight: "20px",
                    marginTop: "0px",
                    marginBottom: "0px",
                    marginLeft: "0px",
                    marginRight: "0px",
                },
                children: [],
            },
            {
                name: "2_2",
                label: "hope_grid",
                icon: "icon-anniu",
                isSelected: false,
                event: "",
                defaultClass: "hope_grid",
                customClass: "g_50",
                style: {
                    width: "50%",
                    height: "500px",
                },
                layout: {
                    paddingTop: "50px",
                    paddingBottom: "50px",
                    paddingLeft: "20px",
                    paddingRight: "20px",
                    marginTop: "0px",
                    marginBottom: "0px",
                    marginLeft: "0px",
                    marginRight: "0px",
                },
                effect: {},
                children: [],
            },
        ],
    },
    g_3: {
        name: "三栏",
        label: "hope_grid",
        icon: "icon-anniu",
        isSelected: false,
        event: "",
        defaultClass: "hope_grid",
        customClass: "g_100",
        style: {
            width: "100%",
        },
        effect: {},
        layout: {},
        children: [
            {
                name: "3_1",
                label: "hope_grid",
                icon: "icon-anniu",
                isSelected: false,
                event: "",
                defaultClass: "hope_grid",
                customClass: "g_30",
                style: {
                    width: "33.3333%",
                },
                effect: {},
                layout: {
                    paddingTop: "50px",
                    paddingBottom: "50px",
                    paddingLeft: "20px",
                    paddingRight: "20px",
                    marginTop: "0px",
                    marginBottom: "0px",
                    marginLeft: "0px",
                    marginRight: "0px",
                },
                children: [],
            },
            {
                name: "3_2",
                label: "hope_grid",
                icon: "icon-anniu",
                isSelected: false,
                event: "",
                defaultClass: "hope_grid",
                customClass: "g_30",
                style: {
                    width: "33.3333%",
                },
                effect: {},
                layout: {
                    paddingTop: "50px",
                    paddingBottom: "50px",
                    paddingLeft: "20px",
                    paddingRight: "20px",
                    marginTop: "0px",
                    marginBottom: "0px",
                    marginLeft: "0px",
                    marginRight: "0px",
                },
                children: [],
            },
            {
                name: "3_3",
                label: "hope_grid",
                icon: "icon-anniu",
                isSelected: false,
                event: "",
                defaultClass: "hope_grid",
                customClass: "g_30",
                style: {
                    width: "33.3333%",
                },
                effect: {},
                layout: {
                    paddingTop: "50px",
                    paddingBottom: "50px",
                    paddingLeft: "20px",
                    paddingRight: "20px",
                    marginTop: "0px",
                    marginBottom: "0px",
                    marginLeft: "0px",
                    marginRight: "0px",
                },
                children: [],
            },
        ],
    },
};
