let basis = {
    mainColor: "rgb(65, 184, 131)",
    subColor: "rgb(165, 184, 131)",
};
export const GridParams = {
    name: "栅格",
    label: "hope_grid",
    icon: "icon-anniu",
    isSelected: false,
    event: "",
    defaultClass:"hope_input",
    customClass: "g_100",
    style: {
        width: "100%",
        height: "auto",
        borderWidth: "1px",
        borderStyle: "dashed",
        paddingTop: "0px",
        paddingBottom: "0px",
        paddingLeft: "0px",
        paddingRight: "0px",
        verticalAlign: "top",
        display: "inline-block",
        fontSize: 0,
    },
    effect: {},
    children: [
        {
            name: "栅格",
            label: "hope_grid",
            icon: "icon-anniu",
            isSelected: false,
            event: "",
            defaultClass:"hope_input",
            customClass: "g_50",
            style: {
                width: "50%",
                height: "auto",
                borderWidth: "1px",
                borderStyle: "dashed",
                paddingTop: "20px",
                paddingBottom: "20px",
                paddingLeft: "20px",
                paddingRight: "20px",
                verticalAlign: "top",
                display: "inline-block",
                fontSize: 0,
            },
            effect: {},
            children: [],
        },
        {
            name: "栅格",
            label: "hope_grid",
            icon: "icon-anniu",
            isSelected: false,
            event: "",
            defaultClass:"hope_input",
            customClass: "g_50",
            style: {
                width: "50%",
                // height: "100%",
                borderWidth: "1px",
                borderStyle: "dashed",
                paddingTop: "20px",
                paddingBottom: "20px",
                paddingLeft: "20px",
                paddingRight: "20px",
                verticalAlign: "top",
                display: "inline-block",
                fontSize: 0,
            },
            effect: {},
            children: [],
        },
    ],
};
