let basis = {
    mainColor: "rgb(65, 184, 131)",
    subColor: "rgb(165, 184, 131)",
};
export const InputParams = {
    name: "文本框",
    label: "hope_input",
    icon: "icon-anniu",
    isSelected: false,
    customClass: "",
    placeholder:"请输入",
    style: {
        width: "100%",
        height: "50px",
        color: "#111",
        fontSize: "16px",
        borderColor: basis.subColor,
        borderWidth: "1px",
        borderStyle: "solid",
        borderRadius: "5px",
        paddingTop: "2px",
        paddingBottom: "2px",
        paddingLeft: "10px",
        paddingRight: "10px",
        verticalAlign: "top",
        display: "inline-block",
        outline: "none",
    },
    effect: {
        width: "100%",
        height: "50px",
        color: "#111",
        fontSize: "16px",
        borderColor: basis.mainColor,
        borderWidth: "1px",
        borderStyle: "solid",
        borderRadius: "5px",
        paddingTop: "2px",
        paddingBottom: "2px",
        paddingLeft: "10px",
        paddingRight: "10px",
        verticalAlign: "top",
        display: "inline-block",
        outline: "none",
    },
};
